#!/bin/sh
set -e
mkdir -p bin
go build -o bin/melodyd ./melodyd/
go build -o bin/melody-tui ./cmd/melody-tui/
go build -o bin/melody-cli ./cmd/melody-cli/
go build -o bin/melody-musiclist ./cmd/melody-musiclist/
go build -o bin/melody-agent ./cmd/melody-agent/
go build -o bin/melody-lrcmatch ./cmd/melody-lrcmatch/
go build -o bin/melody-watcher ./cmd/melody-watcher/
go build -o bin/melody-rofi ./cmd/melody-rofi/
if [ "${GOOS:-$(go env GOOS)}" = "darwin" ]; then
	go build -o bin/melody-macos-agent ./cmd/melody-macos-agent/
fi
